# .streamlit/secrets.toml

[connections.gsheets]
spreadsheet = "PEGA_AQUÍ_LA_URL_COMPLETA_DE_TU_GOOGLE_SHEET"
type = "service_account"
project_id = "del JSON: project_id"
private_key_id = "del JSON: private_key_id"
private_key = "-----BEGIN PRIVATE KEY-----\ndel JSON: private_key (con los \\n tal cual)\n-----END PRIVATE KEY-----\n"
client_email = "del JSON: client_email"
client_id = "del JSON: client_id"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "del JSON: client_x509_cert_url"